[package]
name = "hfqa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.20.0"
clap = {version="4.0.32", features=["derive"]}
anyhow = "1.0.51"
